name: Build and publish release

concurrency:
  group: "release"
  cancel-in-progress: true

on:
  push:
    branches:
      - 'release'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: release

      - name: Test version
        id: version
        run: |
          version=$(cat app/build.gradle.kts | grep -E 'versionName = "' | cut -d \" -f 2)
          if git show-ref --tags --quiet --verify -- "refs/tags/$version" >/dev/null; then
            echo "Git tag $version already exists, failing to publish";
            exit 1
          else
            echo "::set-output name=release_tag::$version"
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Build
        env:
          KEYSTORE_FILE: ./release.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          chmod +x ./gradlew
          echo '${{ secrets.KEYSTORE }}' | base64 -d > ./release.jks
          CI=true RELEASE=true ./gradlew :app:packageReleaseUniversalApk
          mv -T ./app/build/outputs/apk_from_bundle/release/app-release-universal.apk XSpoofSignatures-${{ steps.version.outputs.release_tag }}.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: xspoofsignatures
          path: |
            XSpoofSignatures-${{ steps.version.outputs.release_tag }}.apk

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.release_tag }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: XSpoofSignatures-${{ steps.version.outputs.release_tag }}.apk
